name: Continuous integration

on:
  push:
    paths:
      - "**.js"
      - "**.json"
      - "**.yml"
    branches: ["master", "dev_prod", "dev_featsUser"]
  pull_request:
    branches: ["master", "dev_prod"]

  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0

      - name: Install Dependencies
        run: yarn install

      - name: "Set up Docker"
        run: docker compose up -d
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER_DOCKER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD_DOCKER }}
          POSTGRES_DB: ${{ vars.POSTGRES_DATABASE_DOCKER }}
          POSTGRES_USER_DOCKER: ${{ vars.POSTGRES_USER_DOCKER }}
          POSTGRES_PASSWORD_DOCKER: ${{ vars.POSTGRES_PASSWORD_DOCKER }}
          POSTGRES_DATABASE_DOCKER: ${{ vars.POSTGRES_DATABASE_DOCKER }}
          POSTGRES_HOST_DOCKER: ${{ vars.POSTGRES_HOST_DOCKER }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          DATABASE_URL_DOCKER: ${{ vars.DATABASE_URL_DOCKER }}
          DATABASE_URL: ${{ vars.DATABASE_URL_LOCAL }}

      - name: Set up Prisma
        run: yarn setup:prisma
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL_LOCAL }}

      - name: "Run API and Tests"
        run: |
          yarn dev:actions &

          for i in {1..30}; do
          nc -z localhost 8080 && echo "API is up" && break
          echo "Waiting for API..."
          sleep 1
          done

          yarn test:actions
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL_LOCAL }}
          HOST: ${{ vars.HOST }}
          PORT: ${{ vars.PORT }}
          SECRET: ${{ secrets.SECRET }}
          EXPIRES_IN: ${{ vars.EXPIRES_IN }}
          BASE_URL: ${{ vars.BASE_URL }}