name: Continuous integration

on:
  push:
    paths:
      - "**.ts"
      - "**.json"
      - "**.yml"
    branches: ["master", "dev_prod", "dev_featsUser"]
  pull_request:
    branches: ["master", "dev_prod"]

  workflow_dispatch:

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: yarn install

      - name: "Set up Docker"
        run: docker compose up -d
        env:
          POSTGRES_USER_DOCKER: ${{ vars.POSTGRES_USER_DOCKER }}
          POSTGRES_PASSWORD_DOCKER: ${{ vars.POSTGRES_PASSWORD_DOCKER }}
          POSTGRES_DATABASE_DOCKER: ${{ vars.POSTGRES_DATABASE_DOCKER }}
          DATABASE_URL: ${{ vars.DATABASE_URL_LOCAL }}

      - name: Set up Prisma
        run: yarn setup:prisma
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL_DOCKER }}

      - name: "Run Tests"
        run: yarn test:actions
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL_LOCAL }}
          HOST: ${{ vars.HOST }}
          PORT: ${{ vars.PORT }}
          SECRET: ${{ secrets.SECRET }}
          EXPIRES_IN: ${{ vars.EXPIRES_IN }}
          BASE_URL: ${{ vars.BASE_URL }}
          DATABASE_URL: ${{ vars.DATABASE_URL_DOCKER }}